apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: k8s-task-deplyoment
  labels:
    app: k8s-task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-task-app
  template:
    metadata:
      labels:
        app: k8s-task-app
    spec:
      containers:
        - name: k8s-task
          image: tardis5159/k8s-task:latest
          ports:
            - name: app-port
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8000
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
            initialDelaySeconds: 20